<?php


/**
 * Test class for Tk_Util_HitManager.
 * Generated by PHPUnit on 2012-05-25 at 11:29:36.
 */
class Tk_Util_HitManagerTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var Tk_Util_HitManager
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Tk_Util_HitManager();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Tk_Util_HitManager::processHit
     * @todo Implement testProcessHit().
     */
    public function testProcessHit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
