<?php


/**
 * Test class for Tk_Web_DebugConsole.
 * Generated by PHPUnit on 2012-05-25 at 11:29:44.
 */
class Tk_Web_DebugConsoleTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var Tk_Web_DebugConsole
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        //$this->object = new Tk_Web_DebugConsole();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Tk_Web_DebugConsole::addExtra
     * @todo Implement testAddExtra().
     */
    public function testAddExtra()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Tk_Web_DebugConsole::gentime
     * @todo Implement testGentime().
     */
    public function testGentime()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Tk_Web_DebugConsole::getHtml
     * @todo Implement testGetHtml().
     */
    public function testGetHtml()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
