<?php


/**
 * Test class for Tk_Object.
 * Generated by PHPUnit on 2012-05-25 at 11:29:34.
 */
class Tk_ObjectTest extends TestCase
{

    /**
     * @var Tk_Object
     */
    protected $object;
    
    
    function __construct($name = NULL, array $data = array(), $dataName = '')
    {
        parent::__construct($name, $data, $dataName);
    }
    
    
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Tk_Object();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Tk_Object::getId
     * @todo Implement testGetId().
     */
    public function testObject()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }


}

?>
