<?php


/**
 * Test class for Tk_Request.
 * Generated by PHPUnit on 2012-05-25 at 11:29:33.
 */
class Tk_RequestTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var Tk_Request
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Tk_Request();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Tk_Request::getInstance
     * @todo Implement testGetInstance().
     */
    public function testGetInstance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Tk_Request::getReferer
     * @todo Implement testGetReferer().
     */
    public function testGetReferer()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Tk_Request::getRequestUri
     * @todo Implement testGetRequestUri().
     */
    public function testGetRequestUri()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Tk_Request::setParameter
     * @todo Implement testSetParameter().
     */
    public function testSetParameter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Tk_Request::getParameter
     * @todo Implement testGetParameter().
     */
    public function testGetParameter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Tk_Request::getParameterValues
     * @todo Implement testGetParameterValues().
     */
    public function testGetParameterValues()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Tk_Request::getAllParameters
     * @todo Implement testGetAllParameters().
     */
    public function testGetAllParameters()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Tk_Request::getParameterNames
     * @todo Implement testGetParameterNames().
     */
    public function testGetParameterNames()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Tk_Request::existsParameter
     * @todo Implement testExistsParameter().
     */
    public function testExistsParameter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Tk_Request::getRemoteHost
     * @todo Implement testGetRemoteHost().
     */
    public function testGetRemoteHost()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Tk_Request::getRemoteAddr
     * @todo Implement testGetRemoteAddr().
     */
    public function testGetRemoteAddr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Tk_Request::getRemoteAddrAlt
     * @todo Implement testGetRemoteAddrAlt().
     */
    public function testGetRemoteAddrAlt()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Tk_Request::getUserAgent
     * @todo Implement testGetUserAgent().
     */
    public function testGetUserAgent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Tk_Request::getMethod
     * @todo Implement testGetMethod().
     */
    public function testGetMethod()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Tk_Request::getRawPostData
     * @todo Implement testGetRawPostData().
     */
    public function testGetRawPostData()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Tk_Request::set
     * @todo Implement testSet().
     */
    public function testSet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Tk_Request::get
     * @todo Implement testGet().
     */
    public function testGet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Tk_Request::getList
     * @todo Implement testGetList().
     */
    public function testGetList()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Tk_Request::exists
     * @todo Implement testExists().
     */
    public function testExists()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Tk_Request::referer
     * @todo Implement testReferer().
     */
    public function testReferer()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Tk_Request::requestUri
     * @todo Implement testRequestUri().
     */
    public function testRequestUri()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Tk_Request::agent
     * @todo Implement testAgent().
     */
    public function testAgent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Tk_Request::remoteAddr
     * @todo Implement testRemoteAddr().
     */
    public function testRemoteAddr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Tk_Request::remoteHost
     * @todo Implement testRemoteHost().
     */
    public function testRemoteHost()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
