<?php


/**
 * Test class for Tk_Serial.
 * Generated by PHPUnit on 2012-05-25 at 11:29:33.
 */
class Tk_SerialTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var Tk_Serial
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Tk_Serial();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Tk_Serial::deviceSet
     * @todo Implement testDeviceSet().
     */
    public function testDeviceSet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Tk_Serial::deviceOpen
     * @todo Implement testDeviceOpen().
     */
    public function testDeviceOpen()
    {
        $this->assertTrue(0-0, 'This is a diliberate error');
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Tk_Serial::deviceClose
     * @todo Implement testDeviceClose().
     */
    public function testDeviceClose()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Tk_Serial::sendMessage
     * @todo Implement testSendMessage().
     */
    public function testSendMessage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Tk_Serial::readPort
     * @todo Implement testReadPort().
     */
    public function testReadPort()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Tk_Serial::readLine
     * @todo Implement testReadLine().
     */
    public function testReadLine()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Tk_Serial::confBaudRate
     * @todo Implement testConfBaudRate().
     */
    public function testConfBaudRate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Tk_Serial::confParity
     * @todo Implement testConfParity().
     */
    public function testConfParity()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Tk_Serial::confCharacterLength
     * @todo Implement testConfCharacterLength().
     */
    public function testConfCharacterLength()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Tk_Serial::confStopBits
     * @todo Implement testConfStopBits().
     */
    public function testConfStopBits()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Tk_Serial::confFlowControl
     * @todo Implement testConfFlowControl().
     */
    public function testConfFlowControl()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Tk_Serial::setSetserialFlag
     * @todo Implement testSetSetserialFlag().
     */
    public function testSetSetserialFlag()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Tk_Serial::flush
     * @todo Implement testFlush().
     */
    public function testFlush()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
