<?php
namespace App\Db;

use Tk\Db\Map\Model;


/**
 * Class User
 *
 * @author Michael Mifsud <info@tropotek.com>
 * @link http://www.tropotek.com/
 * @license Copyright 2015 Michael Mifsud
 */
class Content extends Model
{
    
    /**
     * @var int
     */
    public $id = 0;

    /**
     * @var int
     */
    public $pageId = 0;

    /**
     * @var int
     */
    public $userId = 0;

    /**
     * @var string
     */
    public $html = '';

    /**
     * @var string
     */
    public $keywords = '';

    /**
     * @var string
     */
    public $description = '';

    /**
     * @var string
     */
    public $css = '';

    /**
     * @var string
     */
    public $js = '';

    /**
     * Bytes 
     * @var integer
     */
    public $size = 0;

    /**
     * @var \DateTime
     */
    public $modified = null;

    /**
     * @var \DateTime
     */
    public $created = null;

    
    

    /**
     * User constructor.
     * 
     */
    public function __construct()
    {
        $this->modified = new \DateTime();
        $this->created = new \DateTime();
    }

    
    public function save()
    {
        // TODO: calculate content size...
        
        return parent::save(); // TODO: Change the autogenerated stub
    }


}

class ContentValidator extends \App\Helper\Validator
{

    /**
     * Implement the validating rules to apply.
     *
     */
    protected function validate()
    {
        /** @var Content $obj */
        $obj = $this->getObject();

        if (!$obj->pageId) {
            $this->addError('pageId', 'Invalid page ID value.');
        }
        if (!$obj->userId) {
            $this->addError('userId', 'Invalid user ID value.');
        }
        
        // TODO: ????
        
        
    }
}